server:
  port: 8080

spring:
  application:
    name: rate-limiter-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

management:
  endpoints:
    web:
      exposure:
        include: health,info
